pull_request_rules:
  - name: Automatic label for scala-steward PRs
    conditions:
      - author=stryker-scala-steward[bot]
    actions:
      label:
        add:
          - dependencies
  - name: Automatic merge for scala-steward PRs
    conditions:
      - author=stryker-scala-steward[bot]
      - body~=labels:.*semver-(minor|patch)
      # Unfortunately we have to define every CI action. When the build starts there are 0 checks, so each (of the zero) is succesful
      - status-success~=^Test on JDK .*
      - status-success=sbt plugin scripted tests
      - status-success=Test Maven plugin
      - status-success=Test formatting
    actions:
      merge:
        method: squash
