language: scala

scala:
  - 2.12.8

jdk:
  - oraclejdk8
  - openjdk11
  
script:
  - sbt clean coverage test coverageReport

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  # These directories are cached to S3 at the end of the build
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
