language: scala

scala:
  - 2.12.8

jdk:
  - oraclejdk8
  - openjdk11

stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)

jobs:
  include:
    # Default stage test is already added
    - stage: test
      script:
        - sbt 'set version in ThisBuild := "SET-BY-SBT-SNAPSHOT"' stryker4s-core/publishM2 # So maven can find the dependency
        - cd runners/maven
        - mvn test
      jdk: openjdk11
      name: Maven plugin
    - name: Test formatting
      script: ./bin/scalafmt --test
    # run ci-release only if previous stages passed
    - stage: release
      script: sbt ci-release
      jdk: openjdk11
      env:
        - CI_RELEASE=stryker4sPublishSigned
        - CI_SNAPSHOT_RELEASE=stryker4sPublish

script: sbt clean coverage test coverageReport

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
  # Don't cache built dependencies
  - rm -rf $HOME/.ivy2/cache/io.stryker-mutator
  - rm -rf $HOME/.m2/repository/io/stryker-mutator

cache:
  # These directories are cached to S3 at the end of the build
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.m2/repository
    - $HOME/.cache/coursier # Used by scalafmt script

before_install:
  # Ensure that git tags are always fetched so that sbt-dynver can pick up the correct version
  - git fetch --tags
