addSbtPlugin("com.geirsson" % "sbt-ci-release" % "1.5.4")
addSbtPlugin("io.stryker-mutator" % "sbt-stryker4s" % "0.10.0-RC3")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.15")
addSbtPlugin("com.eed3si9n" % "sbt-projectmatrix" % "0.6.0")
addSbtPlugin("ch.epfl.lamp" % "sbt-dotty" % "0.4.5")
