addSbtPlugin("com.geirsson" % "sbt-ci-release" % "1.5.5")
addSbtPlugin("io.stryker-mutator" % "sbt-stryker4s" % "0.10.0-COVERAGE-SNAPSHOT")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.16")
addSbtPlugin("com.eed3si9n" % "sbt-projectmatrix" % "0.7.0")
addSbtPlugin("ch.epfl.lamp" % "sbt-dotty" % "0.5.0")
