name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test on JDK ${{matrix.java-version}}
    strategy:
      fail-fast: false
      matrix:
        java-version: ["openjdk@1.8", "openjdk@1.11"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.cache/coursier/v1
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/project/Dependencies.scala') }}
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: ${{ matrix.java-version }}
      - name: Run tests
        run: csbt 'compile; ++2.13.3 test'
  sbt-scripted:
    name: sbt plugin scripted tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.cache/coursier/v1
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/project/Dependencies.scala') }}
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: openjdk@1.11
      - name: Run tests
        # Only publish stryker4s-core, sbt-stryker4s is published by scripted tests
        run: csbt 'stryker4s-coreJVM2_12/publishLocal; scripted sbt-stryker4s/test-1'
  maven-plugin:
    name: Test Maven plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache SBT & Maven
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.cache/coursier/v1
            ~/.m2/repository
            !~/.m2/repository/io/stryker-mutator/*stryker4s*/
          key: ${{ runner.os }}-maven-${{ hashFiles('**/project/Dependencies.scala') }}-${{ hashFiles('**/pom.xml') }}
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: openjdk@1.11
      - name: Publish stryker4s-core
        run: csbt 'set version in ThisBuild := "SET-BY-SBT-SNAPSHOT"' stryker4s-coreJVM2_12/publishM2
      - name: Run Maven tests
        run: |
          cd maven
          mvn verify -B --no-transfer-progress
  formatting:
    name: Test formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Coursier
        uses: actions/cache@v2
        with:
          path: ~/.cache/coursier/v1
          key: ${{ runner.os }}-coursier-scalafmt-${{ hashFiles('**/bin/scalafmt') }}
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Test formatting
        run: ./bin/scalafmt --test
