name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test on JDK ${{matrix.java-version}}
    strategy:
      fail-fast: false
      matrix:
        java-version: ['openjdk@1.11', 'zulu@1.16']
        os: ['ubuntu-latest', 'windows-latest']
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: coursier/cache-action@v6
      - uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
      - name: Run tests
        run: sbt 'compile; ++2.13.3 test'
  sbt-scripted:
    name: sbt plugin scripted tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: coursier/cache-action@v6
      - uses: actions/setup-java@v2
        with:
          java-version: openjdk@1.11
      - name: Run tests
        # Only publish stryker4s-core -api and -testrunner, sbt-stryker4s is published by scripted tests
        run: sbt 'stryker4s-core2_12/publishLocal; stryker4s-api2_12/publishLocal; sbt-stryker4s-testrunner2_12/publishLocal; scripted sbt-stryker4s/test-1'
  maven-plugin:
    name: Test Maven plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: coursier/cache-action@v6
      - name: Cache Maven
        uses: actions/cache@v2.1.5
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/io/stryker-mutator/stryker4s*/SET-BY-SBT-SNAPSHOT
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - uses: actions/setup-java@v2
        with:
          java-version: openjdk@1.11
      - name: Publish stryker4s-core
        run: sbt 'set ThisBuild / version := "SET-BY-SBT-SNAPSHOT"; stryker4s-api2_12/publishM2; stryker4s-core2_12/publishM2'
      - name: Run Maven tests
        run: |
          cd maven
          mvn verify -B --no-transfer-progress
  formatting:
    name: Test formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: coursier/cache-action@v6
        with:
          extraFiles: 'bin/scalafmt,.scalafmt.conf'
          extraKey: 'scalafmt'
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Test formatting
        run: ./bin/scalafmt --test
  release:
    needs: [test, sbt-scripted, maven-plugin, formatting]
    if: "github.event_name == 'push'
      && startsWith(github.event.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          # Fetch all commits, used by sbt-dynver plugin to determine version
          fetch-depth: 0
      # Fetch all tags
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - uses: coursier/cache-action@v6
      - uses: actions/setup-java@v2
        with:
          java-version: openjdk@1.11
      - name: Publish
        run: sbt ci-release
        env:
          CI_RELEASE: stryker4sPublishSigned
          CI_SNAPSHOT_RELEASE: stryker4sPublish
          CI_SONATYPE_RELEASE: stryker4sReleaseAll
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
