name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test on JDK ${{matrix.java-version}}
    strategy:
      fail-fast: false
      matrix:
        java-version: ['openjdk@1.8', 'openjdk@1.11', 'openjdk@1.14']
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v5
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.java-version }}
      - name: Run tests
        run: csbt 'compile; ++2.13.3 test'
  sbt-scripted:
    name: sbt plugin scripted tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v5
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: openjdk@1.11
      - name: Run tests
        # Only publish stryker4s-core -api and -testrunner, sbt-stryker4s is published by scripted tests
        run: csbt 'stryker4s-core2_12/publishLocal; stryker4s-api2_12/publishLocal; sbt-stryker4s-testrunner2_12/publishLocal; scripted sbt-stryker4s/test-1'
  maven-plugin:
    name: Test Maven plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v5
      - name: Cache Maven
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/io/stryker-mutator/*stryker4s*/
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: openjdk@1.11
      - name: Publish stryker4s-core
        run: csbt 'set version in ThisBuild := "SET-BY-SBT-SNAPSHOT"; stryker4s-core2_12/publishM2'
      - name: Run Maven tests
        run: |
          cd maven
          mvn verify -B --no-transfer-progress
  formatting:
    name: Test formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v5
        with:
          extraFiles: 'bin/scalafmt,.scalafmt.conf'
          extraKey: 'scalafmt'
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Test formatting
        run: ./bin/scalafmt --test
