name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test on JDK ${{matrix.java-version}}
    strategy:
      matrix:
        java-version: [ '1.8', '11' ]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}
    - name: Run tests
      run: sbt test
  formatting:
    name: Test formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Test formatting
        run: ./bin/scalafmt --test
