name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test on JDK ${{matrix.java-version}}
    strategy:
      fail-fast: false
      matrix:
        java-version: ['openjdk@1.8', 'openjdk@1.11']
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: ${{ matrix.java-version }}
      - name: Run tests
        run: csbt +compile test
  sbt-scripted:
    name: sbt plugin scripted tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: openjdk@1.11
      - name: Run tests
        # Only publish stryker4s-core, sbt-stryker4s is published by scripted tests
        run: csbt 'stryker4s-core/publishLocal; scripted sbt-stryker4s/test-1'
  maven-plugin:
    name: Test Maven plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: openjdk@1.11
      - name: Publish stryker4s-core
        run: csbt 'set version in ThisBuild := "SET-BY-SBT-SNAPSHOT"' stryker4s-core/publishM2
      - name: Run Maven tests
        run: |
          cd runners/maven
          mvn verify -B --no-transfer-progress
  formatting:
    name: Test formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Test formatting
        run: ./bin/scalafmt --test
