name: mutation testing

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - test/**

jobs:
  core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Fetch all commits, used by sbt-dynver plugin to determine version
          fetch-depth: 0
      - uses: coursier/cache-action@v6
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Create Stryker4s config
        run: echo 'stryker4s{reporters=["console","dashboard"],base-dir="core",dashboard.module="core"}' > stryker4s.conf
      - name: Run Stryker4s
        run: sbt 'project stryker4s-core; stryker'
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

  command-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Fetch all commits, used by sbt-dynver plugin to determine version
          fetch-depth: 0
      - uses: coursier/cache-action@v6
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Create Stryker4s config
        run: echo 'stryker4s{reporters=["console","dashboard"],base-dir="command-runner",dashboard.module="command-runner"}' > stryker4s.conf
      - name: Run Stryker4s
        run: sbt 'project stryker4s-command-runner; stryker'
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

  maven-plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Fetch all commits, used by sbt-dynver plugin to determine version
          fetch-depth: 0
      - uses: coursier/cache-action@v6
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
      - name: Publish Stryker4s maven deps locally
        run: sbt 'publishM2Local'
      - name: Run Stryker4s
        run: |
          cd maven
          mvn -B --no-transfer-progress stryker4s:run
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
