name: mutation testing

on:
  push:
  # push:
    # branches:
    #   # TODO: Change ran branches to master before merging
    #   - master

jobs:
  core:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version: ["openjdk@1.11"]
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: ${{ matrix.java-version }}
      - name: Run Stryker4s
        run: |
          echo 'stryker4s{reporters=["console","dashboard"],base-dir="core",dashboard.module="core"}' > stryker4s.conf
          csbt 'project stryker4s-core; stryker'
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

  command-runner:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version: ["openjdk@1.11"]
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: ${{ matrix.java-version }}
      - name: Run Stryker4s
        run: |
          echo 'stryker4s{reporters=["console","dashboard"],base-dir="runners/command-runner",dashboard.module="command-runner"}' > stryker4s.conf
          csbt 'project stryker4s-command-runner; stryker'
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

  maven-plugin:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version: ["openjdk@1.11"]
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: ${{ matrix.java-version }}
      - name: Run Stryker4s
        run: |
          cd runners/maven
          echo 'stryker4s{reporters=["console","dashboard"],dashboard.module="maven-plugin"}' > stryker4s.conf
          mvn stryker4s:run
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
