name: release-please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ vars.STRYKER_MUTATOR_APP_ID }}
          private_key: ${{ secrets.STRYKER_MUTATOR_NPA_KEY }}
      - uses: googleapis/release-please-action@v4
        with:
          # Version is determined by sbt-ci-release (which uses sbt-dynver)
          # Actual release code is in `./ci.yml`
          release-type: simple
          token: ${{ steps.generate-token.outputs.token }}
