name: Release
on:
  push:
    branches: [master]
    tags: ['*']
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          # Fetch all commits, used by sbt-dynver plugin to determine version
          fetch-depth: 0
      # Fetch all tags
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - uses: coursier/cache-action@v6
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: openjdk@1.11
      - name: Publish
        run: sbt ci-release
        env:
          CI_RELEASE: stryker4sPublishSigned
          CI_SNAPSHOT_RELEASE: stryker4sPublish
          CI_SONATYPE_RELEASE: stryker4sReleaseAll
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
