name: Release
on:
  push:
    branches: [master]
    tags: ['*']
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Fetch all commits, used by sbt-dynver plugin to determine version
          fetch-depth: 0
      # Fetch all tags
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Cache SBT & Maven
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.cache/coursier/v1
            ~/.m2/repository
            !~/.m2/repository/io/stryker-mutator/*stryker4s*/
          key: ${{ runner.os }}-release-${{ hashFiles('**/project/Dependencies.scala') }}-${{ hashFiles('**/pom.xml') }}
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: openjdk@1.11
      - uses: olafurpg/setup-gpg@v2
      - name: Publish
        run: csbt ci-release
        env:
          CI_RELEASE: stryker4sPublishSigned
          CI_SNAPSHOT_RELEASE: stryker4sPublish
          CI_SONATYPE_RELEASE: stryker4sReleaseAll
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
