name: release-please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          # Version is determined by sbt-ci-release (which uses sbt-dynver)
          # Actual release code is in `./ci.yml`
          release-type: simple
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
