name: Release
on:
  push:
    branches: [master]
    tags: ['*']
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Fetch all commits, used by sbt-dynver plugin to determine version
          fetch-depth: 0
      # Fetch all tags
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/project/Dependencies.scala') }}
      - name: Cache Coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier/v1
          key: ${{ runner.os }}-coursier-${{ hashFiles('**/project/Dependencies.scala') }}
      - name: Cache maven
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: openjdk@1.11
      - uses: olafurpg/setup-gpg@v2
      - name: Publish
        run: csbt ci-release
        env:
          CI_RELEASE: stryker4sPublishSigned
          CI_SNAPSHOT_RELEASE: stryker4sPublish
          CI_SONATYPE_RELEASE: stryker4sReleaseAll
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
